site_name: My Project Documentation
repo_url: https://github.com/siddarthsurana/Go-App
site_description: A brief description of my project.
site_author: Siddarth Surana

# Navigation structure
nav:
  - Overview :
    - Getting started: docs/index.md
plugins:
  - techdocs-core