# Application configuration
app:
  name: todo-api
  image:
    repository: docker.io/sssurana90/go-todo-app
    tag: 8ac7fce6c39ea02bab92e00496516d6899c9f202
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred

# Deployment configuration
deployment:
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  livenessProbe:
    path: /healthz
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    path: /ready
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  host: todo.web.com
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 