name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: sssurana90/go-todo-app
  ARGOCD_SERVER: argocd.example.com
  ARGOCD_APP_NAME: todo-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          
      - name: Run tests
        run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-helm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Helm chart
        run: |
          # Update the image tag in values.yaml
          sed -i "s|repository: .*|repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|g" helm/todo-app/values.yaml
          sed -i "s|tag: .*|tag: ${{ github.sha }}|g" helm/todo-app/values.yaml
          
          # Package the Helm chart
          helm package helm/todo-app
          helm repo index .
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/todo-app/values.yaml
          git commit -m "Update image to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          git push

  # Only run ArgoCD deployment if explicitly enabled
  deploy-argocd:
    needs: update-helm
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Skip ArgoCD deployment
        run: echo "Skipping ArgoCD deployment in GitHub Actions" 